In [ ]:
import torch
from einops import rearrange


In [ ]:


a = torch.tensor([1.1, 2.1, 3.0])
b = torch.tensor([2.5, 1.2, 3.3])
err = rearrange(a, 'n -> n 1') - rearrange(b, 'n -> 1 n')
err = torch.abs(err)
err = torch.where(err > 0.4, err.max()*2, err)





In [ ]:
err

tensor([[4.4000, 0.1000, 4.4000],
        [4.4000, 4.4000, 4.4000],
        [4.4000, 4.4000, 0.3000]])

In [ ]:
from scipy import optimize as sp_optim
r, c = sp_optim.linear_sum_assignment(err)

In [ ]:
r, c

(array([0, 1, 2]), array([1, 0, 2]))

In [ ]:
a[r], b[c]

(tensor([1.1000, 2.1000, 3.0000]), tensor([1.2000, 2.5000, 3.3000]))

## Test match by score

In [ ]:
from bliss.reporting import match_by_score, match_by_score
from bliss.datasets.lsst import BACKGROUND

locs1 = torch.tensor([[1.1, 2.25], [7.1, 7.2], [10, 10]])
locs2 = torch.tensor([[1.2, 2.2], [1.3, 2.35], [7.05, 7.25]])

fluxes1 = torch.tensor([10, 20, 30])
fluxes2 = torch.tensor([5, 11, 32])

r, c, dkeep, _ = match_by_score(locs1=locs1, locs2=locs2, 
                                fluxes1=fluxes1, fluxes2=fluxes2, slack=2, background=10000)

tensor([[ 0.1118,  0.2236,  7.7719],
        [ 7.7337,  7.5606,  0.0707],
        [11.7593, 11.5850,  4.0330]])
tensor([[1.0005, 1.0001, 1.0022],
        [1.0015, 1.0009, 1.0012],
        [1.0025, 1.0019, 1.0002]])
tensor([[ 1.0005,  1.0001, 10.0250],
        [10.0250, 10.0250,  1.0012],
        [10.0250, 10.0250, 10.0250]])


In [ ]:
r, c, dkeep

(array([0, 1, 2]), array([1, 2, 0]), tensor([ True,  True, False]))

In [ ]:
locs1[r], locs2[c]

(tensor([[ 1.1000,  2.2500],
         [ 7.1000,  7.2000],
         [10.0000, 10.0000]]),
 tensor([[1.3000, 2.3500],
         [7.0500, 7.2500],
         [1.2000, 2.2000]]))

In [ ]:
a = torch.randn(3, 2)
torch.where(a > 0, 1, 0)

tensor([[0, 1],
        [0, 0],
        [0, 1]])

## Another example

In [ ]:
from bliss.reporting import match_by_score, match_by_score
from bliss.datasets.lsst import BACKGROUND

locs1 = torch.tensor([[1.1, 2.25], [10, 10]])
locs2 = torch.tensor([[1.2, 2.2], [1.3, 2.35], [1.0, 2.0]])

fluxes1 = torch.tensor([10, 20])
fluxes2 = torch.tensor([5, 20, 11])

r, c, dkeep, _ = match_by_score(locs1=locs1, locs2=locs2, 
                                fluxes1=fluxes1, fluxes2=fluxes2, slack=2, background=1)

In [ ]:
r, c, dkeep

(array([0, 1]), array([2, 0]), tensor([ True, False]))